spring.application.name=demo
# Database URL, Username, and Password
spring.datasource.url=jdbc:sqlite:./data/dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Keep Hibernate aligned with Django schema without auto-altering
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true